import WebVitals from '@/app/_components/web-vitals'
import {productSans} from '@/fonts/fonts'
import '@/styles/globals.css'
import type {Metadata} from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang={'en'}
      suppressHydrationWarning
    >
      <body className={`${productSans.className}`}>
        <WebVitals />
        {children}
      </body>
    </html>
  )
}
